import Link from "next/link";
import { buildPageMetadata } from "../../src/lib/seo";

export const metadata = buildPageMetadata({
  title: "Privacy Policy",
  description: "How KariGO handles personal data across its apps, website and support services.",
  path: "/privacy"
});

export default function PrivacyPage() {
  return <main>
    <section className="section"><p className="eyebrow">Privacy Policy</p><h1>How KariGO handles personal data</h1><p className="lead">KariGO is owned by Zamkah Technologies Limited, the Google Play developer for the Customer, Captain and Partner apps. Zamkah Technologies Limited is the confirmed organisation responsible for the processing described here. The corporate footer does not change that responsibility.</p></section>
    <section className="section soft"><div className="card-grid legal-grid">
      <article className="info-card"><h2>Data we handle</h2><ul className="list"><li>Identity, contact, account, address and profile information.</li><li>Orders, Ride and Delivery activity, support messages, device identifiers and service diagnostics.</li><li>Customer payment references, amounts, status, wallet and purchase history. KariGO uses hosted checkout and does not ask Customers to enter raw card or bank credentials into KariGO.</li><li>Captain location during availability and accepted active work, including background location while an assignment is active.</li><li>Captain and Partner onboarding evidence, and Partner payout bank-account information.</li></ul></article>
      <article className="info-card"><h2>Why we use it</h2><p>We use information to provide accounts, orders, Rides, Deliveries, payments, support, onboarding, fraud and security controls, legal compliance, service communications and reliability. Required and optional fields are identified by the feature that requests them.</p></article>
      <article className="info-card"><h2>Location</h2><p>Customer location supports address, pickup and service-area features. Captain precise location supports availability, navigation and live tracking during accepted work. Background collection is limited to active work and is designed to stop when the job ends. Location is not used for advertising.</p></article>
      <article className="info-card"><h2>Payments</h2><p>Flutterwave hosts supported Customer checkout. KariGO keeps the minimum payment and reconciliation evidence needed for wallet, order, refund, dispute and finance workflows. Legacy provider payloads have been minimized; raw card, bank-account, authorization and provider-customer structures are not retained in those payloads.</p></article>
      <article className="info-card"><h2>Private documents</h2><p>New Captain and Partner onboarding documents use access-controlled Google Cloud Storage. Partner reads are authenticated and backend-mediated, and no permanent public document URL is created. Live deletion can remain recoverable within Google Cloud's seven-day soft-delete window. Provider systems may retain protected copies for longer under their processing terms, so deletion is not described as immediately irreversible.</p></article>
      <article className="info-card"><h2>Historical Partner evidence</h2><p>Seven historical Partner approval records remain as audit history, but their former file objects are unavailable. They are marked for reacquisition. Any replacement is submitted again through the authenticated private-document workflow and linked to the historical record.</p></article>
      <article className="info-card"><h2>Providers and recipients</h2><p>KariGO sends information needed for the relevant flow to providers such as Render, Google Cloud Storage, Flutterwave, Google Maps, Expo/Firebase, Agora and communications providers. A provider may also process information for security, fraud prevention, diagnostics, legal compliance or other purposes described in its terms. Some transfers, including active Google Maps requests, can qualify as sharing under Google Play even when they support a KariGO feature. GCS private document storage is handled under KariGO's accepted Google Cloud data-processing terms.</p></article>
      <article className="info-card"><h2>Website analytics and cookies</h2><p>If you accept website analytics, KariGO may use Google Analytics 4 on public website pages. Google provides the analytics technology. The limited analytics data can include analytics cookies or browser identifiers, a sanitized page path without its query or fragment, safe referrer information, browser and device characteristics, coarse geographic information, timestamps and approved business-interaction events.</p><p>We use this information for aggregate usage measurement, navigation understanding, application-funnel measurement and CTA effectiveness. Analytics remains off unless you accept. You can reject it or later withdraw consent through <strong>Cookie settings</strong> in the site footer.</p><p>KariGO analytics must not intentionally transmit names, email addresses, phone numbers, addresses, message or form contents, payment details, transaction references, account IDs, record IDs, tokens, OTPs, filenames or uploaded documents.</p><p>Analytics retention is configured in Google Analytics rather than by a browser cookie alone. When analytics is activated in the future, KariGO will apply the configured event and user-data retention periods and review aggregate reporting only for as long as needed for the purposes above. Google may process analytics data under its applicable processing terms.</p></article>
      <article className="info-card"><h2>Retention and deletion</h2><p>Account deletion deactivates the selected access, revokes active sessions and deletes eligible unattached private objects after provider confirmation. Orders, financial reconciliation, approved onboarding evidence, disputes, security and audit records may remain only while needed for a defined legal, finance, safety, security or compliance reason. KariGO reviews retained categories and removes or minimises information when the applicable reason no longer requires it.</p><p><Link href="/account-deletion">See the secure deletion process</Link>.</p></article>
      <article className="info-card"><h2>Your choices</h2><p>You can manage permissions, update eligible profile fields, request account deletion and contact support about access or correction. Disabling a permission may prevent the feature that needs it.</p></article>
      <article className="info-card"><h2>Contact</h2><p>Use the <Link href="/contact">KariGO contact and support form</Link>. Do not send passwords, OTPs, card details or provider credentials through a public message.</p></article>
    </div></section>
  </main>;
}
