"use client";
import { useEffect, useState } from "react";
import { vendorApi, VendorProfile } from "../../src/api/vendor.api";
import { DashboardShell, ErrorMessage, Loading } from "../../src/components/dashboard";
import { friendlyError } from "../../src/lib/errors";
export default function Profile() {
  const [profile, setProfile] = useState<VendorProfile | null>(null); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); useEffect(() => { vendorApi.profile().then(setProfile).catch((e) => setError(friendlyError(e))); }, []); if (!profile && !error) return <DashboardShell><Loading /></DashboardShell>;
  return <DashboardShell><header className="topbar"><div><p className="muted">Business settings</p><h1>Profile</h1></div></header><ErrorMessage>{error}</ErrorMessage>{success ? <p className="success">{success}</p> : null}{profile ? <form className="card" onSubmit={async (e) => { e.preventDefault(); try { setError(""); setProfile(await vendorApi.update(profile)); setSuccess("Business profile updated."); } catch (err) { setError(friendlyError(err)); } }}><label>Business name<input value={profile.businessName} onChange={(e) => setProfile({ ...profile, businessName: e.target.value })} /></label><label>Description<textarea value={profile.description ?? ""} onChange={(e) => setProfile({ ...profile, description: e.target.value })} /></label><label>Phone<input value={profile.phoneNumber} onChange={(e) => setProfile({ ...profile, phoneNumber: e.target.value })} /></label><label>Address<input value={profile.address} onChange={(e) => setProfile({ ...profile, address: e.target.value })} /></label><label>City<input value={profile.city} onChange={(e) => setProfile({ ...profile, city: e.target.value })} /></label><label>Logo URL<input value={profile.logoUrl ?? ""} placeholder="https://..." onChange={(e) => setProfile({ ...profile, logoUrl: e.target.value })} /></label><label>Cover image URL<input value={profile.coverImageUrl ?? ""} placeholder="https://..." onChange={(e) => setProfile({ ...profile, coverImageUrl: e.target.value })} /></label><p className="muted">Use only approved public image URLs. Do not paste private storage links or credentials.</p><label><input type="checkbox" checked={profile.isOpen} onChange={(e) => setProfile({ ...profile, isOpen: e.target.checked })} style={{ width: "auto" }} /> Store open</label><button>Save profile</button></form> : null}</DashboardShell>;
}
