"use client";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ordersApi, RejectionReason, VendorOrderDetail } from "../../../src/api/orders.api";
import { DashboardShell, ErrorMessage, Loading, StatusBadge } from "../../../src/components/dashboard";
import { friendlyError, money } from "../../../src/lib/errors";
export default function OrderDetail() {
  const { id } = useParams<{ id: string }>(); const [order, setOrder] = useState<VendorOrderDetail | null>(null); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [reason, setReason] = useState<RejectionReason>("ITEM_UNAVAILABLE"); const [details, setDetails] = useState("");
  const load = () => ordersApi.detail(id).then(setOrder).catch((e) => setError(friendlyError(e))); useEffect(() => { void load(); }, [id]);
  async function act(action: "accept" | "preparing" | "ready") { try { await ordersApi[action](id); setSuccess(action === "accept" ? "Order accepted successfully." : action === "preparing" ? "Order marked as preparing." : "Order marked as ready for pickup."); setError(""); await load(); } catch (e) { setError(friendlyError(e)); } }
  async function reject() { if (!reason) return setError("Please provide a reason before rejecting this order."); if (!window.confirm("Reject this order? Paid orders will require refund review.")) return; try { await ordersApi.reject(id, reason, details || undefined); setSuccess("Order rejected successfully."); setError(""); await load(); } catch (e) { setError(friendlyError(e)); } }
  if (!order && !error) return <DashboardShell><Loading /></DashboardShell>;
  return <DashboardShell><header className="topbar"><div><p className="muted">Order detail</p><h1>{order?.orderNumber}</h1></div>{order ? <StatusBadge>{order.orderStatus.replaceAll("_", " ")}</StatusBadge> : null}</header><ErrorMessage>{error}</ErrorMessage>{success ? <p className="success">{success}</p> : null}{order ? <div className="detail-grid"><div className="section"><article className="card"><h2>Items</h2>{order.items.map((item) => <div className="item" key={item.id}><span>{item.quantity} × {item.productName}<small className="muted">{item.specialInstruction}</small></span><strong>{money(item.totalPrice)}</strong></div>)}</article><article className="card"><h2>Delivery</h2><p>{order.customer.name} · {order.customer.phoneNumber}</p><p>{order.deliveryAddress ? `${order.deliveryAddress.label}: ${order.deliveryAddress.addressLine}, ${order.deliveryAddress.city}, ${order.deliveryAddress.state}` : "No delivery address"}</p><p className="muted">{order.deliveryAddress?.deliveryNote}</p></article><article className="card"><h2>Status history</h2>{order.statusHistory.map((entry) => <p key={entry.id}>{entry.newStatus.replaceAll("_", " ")} · <span className="muted">{new Date(entry.createdAt).toLocaleString()}</span></p>)}</article></div><aside className="section"><article className="card"><h2>Order summary</h2><p>Payment: {order.paymentStatus}</p><p>Subtotal: {money(order.subtotal)}</p><p>Delivery: {money(order.deliveryFee)}</p><strong>Total: {money(order.totalAmount)}</strong></article><article className="card"><h2>Available actions</h2><div className="actions">{order.availableActions.includes("accept") ? <button onClick={() => act("accept")}>Accept order</button> : null}{order.availableActions.includes("preparing") ? <button onClick={() => act("preparing")}>Mark preparing</button> : null}{order.availableActions.includes("ready") ? <button onClick={() => act("ready")}>Ready for pickup</button> : null}</div>{order.availableActions.includes("reject") ? <><select value={reason} onChange={(e) => setReason(e.target.value as RejectionReason)}><option>ITEM_UNAVAILABLE</option><option>VENDOR_CLOSED</option><option>PRICE_ERROR</option><option>TOO_BUSY</option><option>OUT_OF_DELIVERY_WINDOW</option><option>OTHER</option></select><input value={details} onChange={(e) => setDetails(e.target.value)} placeholder="Optional rejection details" /><button className="secondary" onClick={reject}>Reject order</button></> : null}{!order.availableActions.length ? <p className="muted">No vendor actions are valid at this stage.</p> : null}</article></aside></div> : null}</DashboardShell>;
}
