import { router } from "expo-router";
import { useState } from "react";
import { authApi } from "../src/api/auth.api";
import { Button, Card, Field, Message, PasswordField, Protected, Screen } from "../src/components/ui";
import { friendlyError } from "../src/lib/errors";

export default function CaptainPhoneChange() {
  const [newPhoneNumber, setNewPhoneNumber] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [otp, setOtp] = useState(""); const [requestId, setRequestId] = useState(""); const [visible, setVisible] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function submit() { setBusy(true); setError(""); try { if (!requestId) { const result = await authApi.startPhoneChange({ newPhoneNumber, currentPassword }); setRequestId(result.requestId); setMessage(`Code sent to ${result.newPhoneNumberMasked}.`); } else { const result = await authApi.confirmPhoneChange({ requestId, otp }); setMessage(`Phone changed. Sessions were revoked. Payout/security hold until ${result.sensitiveActionsHoldUntil ? new Date(result.sensitiveActionsHoldUntil).toLocaleString() : "review complete"}.`); setTimeout(() => router.replace("/auth/login"), 900); } } catch (cause) { setError(friendlyError(cause)); } finally { setBusy(false); } }
  return <Protected><Screen title="Change phone number" subtitle="Captain phone changes require password confirmation, new-number OTP and a 24-hour sensitive-action hold."><Card><Message>{message}</Message><Message error>{error}</Message>{requestId ? <Field placeholder="6-digit verification code" keyboardType="number-pad" maxLength={6} value={otp} onChangeText={(value) => setOtp(value.replace(/\D/g, ""))} /> : <><Field placeholder="New phone number" keyboardType="phone-pad" value={newPhoneNumber} onChangeText={setNewPhoneNumber} /><PasswordField placeholder="Current password" value={currentPassword} onChangeText={setCurrentPassword} visible={visible} onToggleVisible={() => setVisible(!visible)} /></>}<Button title={busy ? "Working..." : requestId ? "Verify and change" : "Send verification code"} disabled={busy} onPress={() => void submit()} /><Message>Lost your SIM? Contact Captain Support. Recovery requires an audited identity review and never bypasses verification.</Message></Card></Screen></Protected>;
}
